//! レンダーグラフ + リソースシステム。エンジン中核の型安全層。責務: Vulkan(ash) の unsafe を内部に封じ込め、上位層には安全な型を公開する。注意: 公開APIに ash の型（vk::* やハンドル）を露出してはならない。
pub mod atmosphere;
pub mod atmosphere_lut_input;
pub mod atmosphere_lut_probe;
pub mod auto_exposure;
pub mod cascade;
mod clear_color;
mod cloth_material;
mod cloth_shader_set;
mod compute_shader;
mod descriptor_indexing_limits;
pub mod distant_environment;
mod draw_bundle_id;
mod draw_result;
mod error;
mod extent;
mod frame_composition;
pub mod frame_input;
mod frame_lighting;
mod gpu_memory_stats;
pub mod gpu_pass_timing;
pub mod indirect_lighting;
mod lighting_input;
#[cfg(test)]
mod lighting_input_tests;
mod lod_mesh;
mod material;
mod material_table_summary;
mod numeric;
mod particle_material;
mod particle_shader_set;
mod pbr_material;
mod present_display;
mod readback_image;
mod readback_result;
mod render_object_material;
mod render_scene_material;
mod renderer;
mod shader_bundle;
mod shader_set;
mod skin_mesh;
mod terrain_detail;
mod texture_material;
mod ui_draw_data;
mod ui_mesh;
mod ui_scissor;
mod ui_texture_id;
mod ui_texture_material;
mod ui_vertex;
mod validation_counter;
mod vertex;
mod view_input;
mod visible_instance_selection;
mod vulkan;
mod vulkan_failure;
pub use clear_color::{クリアカラー, クリアカラーエラー};
pub use cloth_material::{布定数, 布素材, 布素材エラー};
pub use cloth_shader_set::布シェーダー一式;
pub use compute_shader::コンピュートシェーダー;
pub use descriptor_indexing_limits::ディスクリプタ索引上限;
pub use draw_bundle_id::描画束ID;
pub use draw_result::{描画結果, 見送り理由};
pub use error::{レンダラーエラー, 布エラー};
pub use extent::ウィンドウ寸法;
pub use frame_composition::{フレーム構成, フレーム構成エラー, フレーム段階};
pub use frame_input::{フレーム描画入力, 布フレーム入力, 空入力, 空入力の材料, 空入力エラー};
pub use gpu_memory_stats::{GPUメモリ用途, GPUメモリ用途別確保量, GPUメモリ統計};
pub use lighting_input::{ライティング入力, ライティング入力エラー, 光強度, 光色, 影の落ち方};
pub use lighting_input::{影入力, 影正射影範囲, 方向光入力, 点光源入力, 環境光係数};
pub use lod_mesh::{メッシュ素材, 詳細段メッシュ列};
pub use material::マテリアル素材;
pub use material_table_summary::材質資源表の要約;
pub use particle_material::{粒子素材, 粒子素材エラー};
pub use particle_shader_set::{粒子シェーダー一式, 粒子シェーダー一式エラー};
pub use pbr_material::{マテリアル素材エラー, 金属粗さPBR素材};
pub use present_display::{実表示観測, 実表示計測状況, 実表示計測要求};
pub use readback_image::{HDR読み戻し画像, 読み戻し画像};
pub use readback_result::読み戻し結果;
pub use render_object_material::{個体変換列, 描画対象素材, 材質スロット素材, 材質スロット素材一覧};
pub use render_scene_material::描画シーン素材;
pub use renderer::{
    CPU区間時間, パス別描画発行, レンダラー, 大気のベイク済み画像生成パス数の記録, 描画発行内訳, 段別個体数, 記録側の計数, 間接照明生成パス数の記録,
};
pub use shader_bundle::{シェーダー束, 大気のベイク済み画像のシェーダー一式, 空シェーダー};
pub use shader_set::{シェーダー一式, シェーダー一式エラー};
pub use skin_mesh::{スキンメッシュ素材, スキンメッシュ素材エラー, スキン頂点属性};
pub use terrain_detail::{地形詳細段, 地形詳細段選択};
pub use texture_material::{テクスチャ用途, テクスチャ素材, テクスチャ素材エラー};
pub use ui_draw_data::UI描画データ;
pub use ui_mesh::UIメッシュ;
pub use ui_scissor::UIシザー矩形px;
pub use ui_texture_id::UIテクスチャID;
pub use ui_texture_material::{UIテクスチャ素材, UIテクスチャ素材エラー};
pub use ui_vertex::UI頂点;
pub use validation_counter::{検証カウンタ, 検証層の状況};
pub use vertex::頂点;
pub use view_input::{描画視点, 描画視点一覧};
pub use visible_instance_selection::{パス別描画範囲, 可視ID列を読むパス数, 可視ID列エラー, 可視パス};
pub use visible_instance_selection::{可視個体選択, 可視個体選択一覧, 段別描画範囲};
pub use vulkan_failure::Vulkan失敗コード;
