//! Vulkan(ash) の unsafe をこの階層の実装内部に封じ込める内部モジュール群。
//! ここに置く型・関数はすべて `pub(crate)`。上位公開APIは親クレートの各ファイルが担う。
//!
//! 参照: CLAUDE.md「unsafe の規律」

pub(crate) mod atmosphere_lut;
pub(crate) mod auto_exposure;
pub(crate) mod bloom;
pub(crate) mod bloom_targets;
pub(crate) mod cloth;
pub(crate) mod cloth_shadow;
pub(crate) mod commands;
pub(crate) mod compute_pipeline;
pub(crate) mod debug_messenger;
pub(crate) mod depth;
pub(crate) mod depth_injection;
pub(crate) mod derived_environment;
pub(crate) mod descriptor;
pub(crate) mod descriptor_indexing;
pub(crate) mod device;
pub(crate) mod device_buffer;
pub(crate) mod distant_environment;
pub(crate) mod frame;
pub(crate) mod fullscreen_pipeline;
pub(crate) mod geometry;
pub(crate) mod gpu_environment;
pub(crate) mod gpu_timing;
pub(crate) mod graph;
pub(crate) mod hdr_target;
pub(crate) mod headless;
pub(crate) mod host_buffer;
pub(crate) mod indirect_lighting;
pub(crate) mod instance;
pub(crate) mod instance_transform;
pub(crate) mod lighting_query;
pub(crate) mod linear_sampler;
pub(crate) mod local_visibility;
pub(crate) mod material_record;
pub(crate) mod material_table;
pub(crate) mod material_variant;
pub(crate) mod memory;
pub(crate) mod memory_ledger;
pub(crate) mod nearest_sampler;
pub(crate) mod particles;
pub(crate) mod physical_device;
pub(crate) mod pipeline;
pub(crate) mod pipeline_ledger;
pub(crate) mod post_process;
pub(crate) mod present_timing;
pub(crate) mod readback;
pub(crate) mod relative_anchor;
pub(crate) mod scene_draw_constants;
pub(crate) mod shader_module;
#[cfg(test)]
pub(crate) mod shader_struct;
pub(crate) mod shadow_map;
pub(crate) mod shadow_push;
pub(crate) mod skinning;
pub(crate) mod sky_stage;
pub(crate) mod surface;
pub(crate) mod swapchain;
pub(crate) mod sync;
pub(crate) mod texture;
pub(crate) mod tonemap;
pub(crate) mod tracked_device;
pub(crate) mod transfer;
pub(crate) mod ui;
pub(crate) mod uniform;
pub(crate) mod visible_id;
