export { 建物の格子の編集モデル } from './建物の格子の編集モデル.ts'
export { 升目の座標が同じか } from './升目の鍵.ts'
export { 全側面, 側面のはめ口を読む } from './升目の側面.ts'
export type { 升目の側面 } from './升目の側面.ts'
export { 初期の建物の格子を作る, 壁を入れない, 壁を入れる } from './初期の建物の格子を作る.ts'
export type { 升目を消せない理由, 升目を置けない理由, 面へ壁を入れられない理由 } from './格子の成り立ちの判定.ts'
export { 隣の座標 } from './隣接の整合をとる.ts'
