[package]
name = "blitz_app"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
blitz_asset_compiler = { path = "../blitz_asset_compiler" }
blitz_engine = { path = "../blitz_engine" }
blitz_math = { path = "../blitz_math" }
blitz_render = { path = "../blitz_render" }
blitz_sim = { path = "../blitz_sim" }
winit = { workspace = true }
raw-window-handle = { workspace = true }
thiserror = { workspace = true }
egui = { workspace = true }
egui-winit = { workspace = true }
