//! 大域世界とチャンクの編集資源(区画割り・道路・建物・散布・マテリアル台帳・建物の格子)と、その操作コマンドの
//! 型宣言の並び。`編集資源契約.ts`へ出す宣言のうち、地形の編集の道具が使う分をこのモジュールが所有する。

use ts_rs::{Config, TS};

pub(super) fn 大域とチャンクの編集の型宣言の並び(設定: &Config) -> [String; 63] {
    [
        <crate::プロジェクト情報応答 as TS>::decl(設定),
        <crate::建物定義の用途 as TS>::decl(設定),
        <crate::ベイ構造 as TS>::decl(設定),
        <crate::建物の入口方向 as TS>::decl(設定),
        <crate::建物の外接箱 as TS>::decl(設定),
        <crate::建物外形定義 as TS>::decl(設定),
        <crate::建物外形カタログ as TS>::decl(設定),
        <crate::壁の種類 as TS>::decl(設定),
        <crate::壁の外面の飾り as TS>::decl(設定),
        <crate::はめ口の値 as TS>::decl(設定),
        <crate::升目の座標 as TS>::decl(設定),
        <crate::升目の床 as TS>::decl(設定),
        <crate::升目の屋根 as TS>::decl(設定),
        <crate::升目の宣言 as TS>::decl(設定),
        <crate::升目の複体 as TS>::decl(設定),
        <crate::建物の格子の装飾 as TS>::decl(設定),
        <crate::建物の格子 as TS>::decl(設定),
        <crate::建物の格子の一覧項目 as TS>::decl(設定),
        <crate::位置3次元 as TS>::decl(設定),
        <crate::チャンク座標 as TS>::decl(設定),
        <crate::世界の区画割り as TS>::decl(設定),
        <crate::広域道路 as TS>::decl(設定),
        <crate::チャンクの道路 as TS>::decl(設定),
        <crate::建物の配置 as TS>::decl(設定),
        <crate::散布の設定 as TS>::decl(設定),
        <crate::散布の個体 as TS>::decl(設定),
        <crate::マテリアル定義 as TS>::decl(設定),
        <crate::層割当 as TS>::decl(設定),
        <crate::マテリアル台帳 as TS>::decl(設定),
        <crate::大域世界構造 as TS>::decl(設定),
        <crate::地表材質層 as TS>::decl(設定),
        <crate::平面の位置 as TS>::decl(設定),
        <crate::等高線 as TS>::decl(設定),
        <crate::粗マスの塗り as TS>::decl(設定),
        <crate::見下ろし図の下書き as TS>::decl(設定),
        <crate::チャンク構造 as TS>::decl(設定),
        <crate::造成筆致種別 as TS>::decl(設定),
        <crate::造成筆致 as TS>::decl(設定),
        <crate::材質の筆致 as TS>::decl(設定),
        <crate::道路対象 as TS>::decl(設定),
        <crate::道路を追加する as TS>::decl(設定),
        <crate::道路を削除する as TS>::decl(設定),
        <crate::道路点を追加する as TS>::decl(設定),
        <crate::道路点を挿入する as TS>::decl(設定),
        <crate::道路点を移動する as TS>::decl(設定),
        <crate::道路点を削除する as TS>::decl(設定),
        <crate::建物を配置する as TS>::decl(設定),
        <crate::建物を移動する as TS>::decl(設定),
        <crate::建物を削除する as TS>::decl(設定),
        <crate::散布設定を変更する as TS>::decl(設定),
        <crate::道路に合わせて切土盛土する as TS>::decl(設定),
        <crate::建物基礎を平坦化する as TS>::decl(設定),
        <crate::急勾配を岩肌へベイクする as TS>::decl(設定),
        <crate::道路下を泥へベイクする as TS>::decl(設定),
        <crate::等高線を追加する as TS>::decl(設定),
        <crate::等高線を変更する as TS>::decl(設定),
        <crate::等高線を削除する as TS>::decl(設定),
        <crate::粗マスを塗る as TS>::decl(設定),
        <crate::等高線から高さ場を生成する as TS>::decl(設定),
        <crate::粗マスから地形を生成する as TS>::decl(設定),
        <crate::高さ場から等高線を導く as TS>::decl(設定),
        <crate::高さ場から粗マスを導く as TS>::decl(設定),
        <crate::編集コマンド as TS>::decl(設定),
    ]
}
