[package]
name = "blitz_asset_compiler"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
blitz_assembly = { path = "../blitz_assembly" }
blitz_engine = { path = "../blitz_engine" }
blitz_math = { path = "../blitz_math" }
thiserror = { workspace = true }
gltf = { workspace = true }
image = { workspace = true }
rayon = { workspace = true }
serde_json = { workspace = true }
